[docker]
  image = "wafflehacks/hackathon-manager"
  tag = "develop"

[dependencies]
  redis = true
  postgres = "DATABASE_URL"

[environment]
  hm_domain_name = "apply.wafflehacks.tech"
  hm_protocol = "https"

  lang = "en_US.UTF-8"
  time_zone = "America/Los_Angeles"

  smtp_authentication = "plain"
  smtp_starttls_auto = "true"

[secrets]
  devise_secret_key = { type = "generate", format = "hex", length = 64 }
  secret_key_base = { type = "generate", format = "hex", length = 64 }

  mlh_key = "load"
  mlh_secret = "load"

  aws_access_key_id = { type = "aws", role = "apply", part = "access" }
  aws_secret_access_key = { type = "aws", role = "apply", part = "secret" }
  aws_bucket = "load"
  aws_region = "load"

  smtp_address = "load"
  smtp_password = "load"
  smtp_port = "load"
  smtp_user_name = "load"

  discord_guild_id = "load"
  discord_client_id = "load"
  discord_client_secret = "load"
