[docker]
  image = "wafflehacks/discord-linking"
  tag = "main"

[dependencies]
  redis = true
  postgres = { name = "DATABASE_URL", role = "discord-linking" }

[web]
  domain = "discord.wafflehacks.org"

[environment]
  debug = "false"

  auth0_domain = "login.wafflehacks.org"

  application_portal_url = "http://integrations.application-portal.wafflemaker.internal:8000"

  nats_url = "nats://172.18.1.2:4222"

  otel_enable = "yes"
  otel_service_name = "discord-linking"
  otel_exporter_otlp_endpoint = "https://api.honeycomb.io"

[secrets]
  secret_key = { type = "generate", format = "base64", length = 64 }

  auth0_client_id = "load"
  auth0_client_secret = "load"

  discord_client_id = "load"
  discord_client_secret = "load"

  aws_access_key = { type = "aws", role = "discord-linking", part = "access" }
  aws_secret_access_key = { type = "aws", role = "discord-linking", part = "secret" }

  otel_exporter_otlp_headers = "load"
