[docker]
  image = "wafflehacks/mailgunner"
  tag = "scheduler-master"

[web]
  enabled = false

[dependencies]
  redis = true
  postgres = { name = "DATABASE_URL", role = "mail" }

[environment]
  debug = "no"

[secrets]
  secret_key = { type = "generate", format = "base64", length = 32 }

  mailgun_api_key = "load"
  mailgun_domain = "load"
  mailgun_webhook_signing_key = "load"

  sentry_dsn = "load"

  aws_access_key_id = { type = "aws", role = "mail", part = "access" }
  aws_secret_access_key = { type = "aws", role = "mail", part = "secret" }
  aws_storage_bucket_name = "load"
  aws_s3_region_name = "load"

  admin_email = "load"
  admin_name = "load"
