[docker]
  image = "wafflehacks/mailgunner"
  tag = "master"

[dependencies]
  redis = true
  postgres = "DATABASE_URL"

[environment]
  debug = "no"
  https = "yes"
  public_url = "https://mail-v2.wafflehacks.tech"

[secrets]
  secret_key = { type = "generate", format = "base64", length = 32 }

  mailgun_api_key = "load"
  mailgun_domain = "load"
  mailgun_webhook_signing_key = "load"
  webhook_secret = "load"

  aws_access_key_id = { type = "aws", role = "mail", part = "access" }
  aws_secret_access_key = { type = "aws", role = "mail", part = "secret" }
  aws_storage_bucket_name = "load"
  aws_s3_region_name = "load"

  discord_guild_id = "load"
  discord_client_id = "load"
  discord_client_secret = "load"

  admin_email = "load"
  admin_name = "load"
