[docker]
  image = "wafflehacks/wafflebot"
  tag = "bot-master"

[web]
  enabled = false

[dependencies]
  redis = true
  postgres = "DATABASE_URL"

[environment]
  full_errors = "no"

  api_secret_key = "unused"
  api_discord_client_id = "unused"
  api_discord_client_secret = "thisisunusedbutmustbeprovided123"
  api_guild_name = "unused"

[secrets]
  discord_token = "load"
