[docker]
  image = "wafflehacks/application-portal"
  tag = "celery-latest"

[dependencies]
  redis = true
  postgres = { name = "DATABASE_URL", role = "application-portal" }

[web]
  enabled = false

[environment]
  apps = "communication"
  
  issuer_url = "https://login.wafflehacks.org/"
  jwks_url = "https://login.wafflehacks.org/.well-known/jwks.json"

  communication_mailer = "http://mailer.wafflemaker.internal:8500"
  communication_mjml_api = "http://mjml.application-portal.wafflemaker.internal:8000"

  communication_sender = "apply@wafflehacks.org"
  communication_reply_to = "team@wafflehacks.org"
