[docker]
  image = "wafflehacks/application-portal"
  tag = "communication-main"

[dependencies]
  redis = true
  postgres = { name = "DATABASE_URL", role = "application-portal" }

[web]
  domain = "api.apply.wafflehacks.org"
  path = "/communication"

[environment]
  apps = "communication"

  issuer_url = "https://login.wafflehacks.org/"
  jwks_url = "https://login.wafflehacks.org/.well-known/jwks.json"

  communication_mailer = "http://mailer.wafflemaker.internal:8500"
  communication_mjml_api = "http://mjml.application-portal.wafflemaker.internal:8000"

  communication_sender = "WaffleHacks Application Portal <apply@wafflehacks.org>"
  communication_reply_to = "team@wafflehacks.org"

  otel_enable = "yes"
  otel_service_name = "application-portal/communication"
  otel_exporter_otlp_endpoint = "https://api.honeycomb.io"

[secrets]
  otel_exporter_otlp_headers = "load"
