[docker]
  image = "wafflehacks/application-portal"
  tag = "sync-latest"

[dependencies]
  redis = true
  postgres = { name = "DATABASE_URL", role = "application-portal" }

[web]
  enabled = false

[environment]
  apps = "sync"

[secrets]
  sync_queue = "load"

  aws_default_region = "load"
  aws_access_key_id = { type = "aws", role = "application-portal.sync", part = "access" }
  aws_secret_access_key = { type = "aws", role = "application-portal.sync", part = "secret" }
