## This file defines the DNS records that should be created for each server.
## The format is:
#
# server-name:
#   - record
#

waffle-primary:
  # Infrastructure services
  - deploy.wafflehacks.tech
  - traefik.wafflehacks.tech
  - vault.wafflehacks.tech

  # Deployed services
  - apply.wafflehacks.tech
  - bot.wafflehacks.tech
  - cms.wafflehacks.tech
